# Generated by Django 5.1 on 2024-08-20 05:05

import destinations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=destinations.models.thumbnail_image_path),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(upload_to=destinations.models.destination_image_path),
        ),
    ]
